package com.my.mirror.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CLASSI_FIED.
 */
public class ClassiFied {

    private Long id;
    private String title;

    public ClassiFied() {
    }

    public ClassiFied(Long id) {
        this.id = id;
    }

    public ClassiFied(Long id, String title) {
        this.id = id;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
