package com.my.mirror.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.my.mirror.greendao.ClassiFied;
import com.my.mirror.greendao.ReUse;
import com.my.mirror.greendao.SpecialShare;
import com.my.mirror.greendao.LoginToken;
import com.my.mirror.greendao.WelcomeIv;

import com.my.mirror.greendao.ClassiFiedDao;
import com.my.mirror.greendao.ReUseDao;
import com.my.mirror.greendao.SpecialShareDao;
import com.my.mirror.greendao.LoginTokenDao;
import com.my.mirror.greendao.WelcomeIvDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig classiFiedDaoConfig;
    private final DaoConfig reUseDaoConfig;
    private final DaoConfig specialShareDaoConfig;
    private final DaoConfig loginTokenDaoConfig;
    private final DaoConfig welcomeIvDaoConfig;

    private final ClassiFiedDao classiFiedDao;
    private final ReUseDao reUseDao;
    private final SpecialShareDao specialShareDao;
    private final LoginTokenDao loginTokenDao;
    private final WelcomeIvDao welcomeIvDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        classiFiedDaoConfig = daoConfigMap.get(ClassiFiedDao.class).clone();
        classiFiedDaoConfig.initIdentityScope(type);

        reUseDaoConfig = daoConfigMap.get(ReUseDao.class).clone();
        reUseDaoConfig.initIdentityScope(type);

        specialShareDaoConfig = daoConfigMap.get(SpecialShareDao.class).clone();
        specialShareDaoConfig.initIdentityScope(type);

        loginTokenDaoConfig = daoConfigMap.get(LoginTokenDao.class).clone();
        loginTokenDaoConfig.initIdentityScope(type);

        welcomeIvDaoConfig = daoConfigMap.get(WelcomeIvDao.class).clone();
        welcomeIvDaoConfig.initIdentityScope(type);

        classiFiedDao = new ClassiFiedDao(classiFiedDaoConfig, this);
        reUseDao = new ReUseDao(reUseDaoConfig, this);
        specialShareDao = new SpecialShareDao(specialShareDaoConfig, this);
        loginTokenDao = new LoginTokenDao(loginTokenDaoConfig, this);
        welcomeIvDao = new WelcomeIvDao(welcomeIvDaoConfig, this);

        registerDao(ClassiFied.class, classiFiedDao);
        registerDao(ReUse.class, reUseDao);
        registerDao(SpecialShare.class, specialShareDao);
        registerDao(LoginToken.class, loginTokenDao);
        registerDao(WelcomeIv.class, welcomeIvDao);
    }
    
    public void clear() {
        classiFiedDaoConfig.getIdentityScope().clear();
        reUseDaoConfig.getIdentityScope().clear();
        specialShareDaoConfig.getIdentityScope().clear();
        loginTokenDaoConfig.getIdentityScope().clear();
        welcomeIvDaoConfig.getIdentityScope().clear();
    }

    public ClassiFiedDao getClassiFiedDao() {
        return classiFiedDao;
    }

    public ReUseDao getReUseDao() {
        return reUseDao;
    }

    public SpecialShareDao getSpecialShareDao() {
        return specialShareDao;
    }

    public LoginTokenDao getLoginTokenDao() {
        return loginTokenDao;
    }

    public WelcomeIvDao getWelcomeIvDao() {
        return welcomeIvDao;
    }

}
