package com.my.mirror.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.my.mirror.greendao.ClassiFied;
import com.my.mirror.greendao.ReUse;

import com.my.mirror.greendao.ClassiFiedDao;
import com.my.mirror.greendao.ReUseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig classiFiedDaoConfig;
    private final DaoConfig reUseDaoConfig;

    private final ClassiFiedDao classiFiedDao;
    private final ReUseDao reUseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        classiFiedDaoConfig = daoConfigMap.get(ClassiFiedDao.class).clone();
        classiFiedDaoConfig.initIdentityScope(type);

        reUseDaoConfig = daoConfigMap.get(ReUseDao.class).clone();
        reUseDaoConfig.initIdentityScope(type);

        classiFiedDao = new ClassiFiedDao(classiFiedDaoConfig, this);
        reUseDao = new ReUseDao(reUseDaoConfig, this);

        registerDao(ClassiFied.class, classiFiedDao);
        registerDao(ReUse.class, reUseDao);
    }
    
    public void clear() {
        classiFiedDaoConfig.getIdentityScope().clear();
        reUseDaoConfig.getIdentityScope().clear();
    }

    public ClassiFiedDao getClassiFiedDao() {
        return classiFiedDao;
    }

    public ReUseDao getReUseDao() {
        return reUseDao;
    }

}
