package com.my.mirror.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RE_USE".
 */
public class ReUse {

    private Long id;
    private String title;
    private String img;
    private String name;
    private String price;
    private String area;
    private String brand;

    public ReUse() {
    }

    public ReUse(Long id) {
        this.id = id;
    }

    public ReUse(Long id, String title, String img, String name, String price, String area, String brand) {
        this.id = id;
        this.title = title;
        this.img = img;
        this.name = name;
        this.price = price;
        this.area = area;
        this.brand = brand;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

}
