package com.my.mirror.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SPECIAL_SHARE".
 */
public class SpecialShare {

    private Long id;
    private String title;
    private String img;

    public SpecialShare() {
    }

    public SpecialShare(Long id) {
        this.id = id;
    }

    public SpecialShare(Long id, String title, String img) {
        this.id = id;
        this.title = title;
        this.img = img;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

}
