package com.my.mirror.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WELCOME_IV".
 */
public class WelcomeIv {

    private Long id;
    private String uri;

    public WelcomeIv() {
    }

    public WelcomeIv(Long id) {
        this.id = id;
    }

    public WelcomeIv(Long id, String uri) {
        this.id = id;
        this.uri = uri;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

}
